### ISSUE TITLE
Crash on the face_alignment.FaceAlignment

### ISSUE THREAD

**Issue by superwhyun** [ITU-T-SG11-Q8/FVapp#5]
It looks like the code is using an unknown enum type, _face_alignment.LandmarksType._2D_.

Need to check.

---
pygame 2.5.2 (SDL 2.28.2, Python 3.11.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Peer API init.
START.....MAIN WINDOWS
cuda is True
/home/whyun/miniconda3/envs/fvapp/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "/home/whyun/workspace/FVapp/main.py", line 1261, in <module>
    predictor = get_predictor()
                ^^^^^^^^^^^^^^^
  File "/home/whyun/workspace/FVapp/main.py", line 1247, in get_predictor
    _predictor = GRMPredictor(
                 ^^^^^^^^^^^^^
  File "/home/whyun/workspace/FVapp/gooroomee/grm_predictor.py", line 50, in __init__
    self.fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=True, device=self.device)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whyun/miniconda3/envs/fvapp/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: _2D

**Comment by superwhyun** [comment]
If you did install packages using requirements.txt, this error will not occur. However, if anyone installed using requirements-latest.txt, you will see the above error message. This is a quick fix for the error.

replace 'TWO_D' with '_2D'

https://github.com/1adrianb/face-alignment
