### ISSUE TITLE
OSError: [Errno -9998] Invalid number of channels

### ISSUE THREAD

**Issue by superwhyun** [ITU-T-SG11-Q8/FVapp#6]
I got following message with crash on trying to run this on Ubuntu without mic

--

pygame 2.5.2 (SDL 2.28.2, Python 3.11.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Peer API init.
START.....MAIN WINDOWS
cuda is True
/home/whyun/miniconda3/envs/fvapp/lib/python3.11/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3526.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Downloading: "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth" to /home/whyun/.cache/torch/hub/checkpoints/s3fd-619a316812.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 85.7M/85.7M [00:30<00:00, 2.94MB/s]
Downloading: "https://www.adrianbulat.com/downloads/python-fan/2DFAN4-cd938726ad.zip" to /home/whyun/.cache/torch/hub/checkpoints/2DFAN4-cd938726ad.zip
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 91.9M/91.9M [00:32<00:00, 2.95MB/s]
camlist:['/dev/video9']
ALSA lib pcm_dsnoop.c:601:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
Input deviceName:HDA NVidia: HDMI 0 (hw:0,3), index:0
Input deviceName:HDA NVidia: HDMI 1 (hw:0,7), index:1
Input deviceName:HDA NVidia: HDMI 2 (hw:0,8), index:2
Input deviceName:HDA NVidia: HDMI 3 (hw:0,9), index:3
Input deviceName:HDA NVidia: HDMI 0 (hw:1,3), index:4
Input deviceName:HDA NVidia: HDMI 1 (hw:1,7), index:5
Input deviceName:HDA NVidia: HDMI 2 (hw:1,8), index:6
Input deviceName:HDA NVidia: HDMI 3 (hw:1,9), index:7
Input deviceName:HD-Audio Generic: HDMI 0 (hw:2,3), index:8
Input deviceName:HD-Audio Generic: HDMI 1 (hw:2,7), index:9
Input deviceName:HD-Audio Generic: HDMI 2 (hw:2,8), index:10
Output deviceName:USB Audio: - (hw:3,0), index:11
Input deviceName:USB Audio: #3 (hw:3,3), index:14
Input deviceName:hdmi, index:15
###key frame period:11000
change device index = [0]
Mic Open, Mic Index:0
Expression 'parameters->channelCount <= maxChans' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1514
Expression 'ValidateParameters( inputParameters, hostApi, StreamDirection_In )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2818
Speaker Open, Index:0
is_server:True, comm_bin:<gooroomee.bin_comm.BINComm object at 0x7f60100c8450>, client_connected:False
start comm server. port:7000
init_server
Traceback (most recent call last):
  File "/home/whyun/workspace/FVapp/main.py", line 158, in run
    self.mic_stream = self.mic_interface.open(format=pyaudio.paInt16, channels=1, rate=44100, input=True,
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whyun/miniconda3/envs/fvapp/lib/python3.11/site-packages/pyaudio/__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/whyun/miniconda3/envs/fvapp/lib/python3.11/site-packages/pyaudio/__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
                   ^^^^^^^^^^^^^^^^^^^^
OSError: [Errno -9998] Invalid number of channels
######## run server [7000]. device:cuda
GrmCommWorker running:True
Aborted (core dumped)

**Comment by superwhyun** [comment]
fixed.

https://github.com/ITU-T-SG11-Q8/FVapp/commit/99f70cf2c85dd9c2815a4601822c1429cd3631b0
https://github.com/ITU-T-SG11-Q8/FVapp/commit/8e6d642cd9f510c8ea4ffc1a5fc47f96f5de2015
